"use client"

import Link from 'next/link'
import Image from 'next/image'

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
      {/* Header/Navigation */}
      <header className="sticky top-0 z-50 bg-[hsl(var(--background))]/90 backdrop-blur-md border-b border-[hsl(var(--border))]/30 py-4">
        <div className="container flex items-center justify-between px-4 mx-auto">
          <div className="flex items-center flex-shrink-0 ml-4 xl:ml-0">
            <Link href="/" className="flex items-center space-x-2">
              <Image src="/favicon/Logo-Fox-Light.svg" alt="Logo" width={36} height={36} className="cursor-pointer" />
            </Link>
          </div>

          <nav className="hidden lg:flex items-center space-x-8">
            <Link href="/" className="text-base font-medium text-[hsl(var(--foreground))] transition-all duration-200 hover:text-opacity-70">
              Home
            </Link>
            <Link href="/pricing" className="text-base font-medium text-[hsl(var(--foreground))] transition-all duration-200 hover:text-opacity-70">
              Pricing
            </Link>
            <Link href="/terms-and-conditions" className="relative text-base font-medium text-[hsl(var(--foreground))] transition-all duration-200 group">
              Terms
              <span className="absolute -bottom-1 left-0 w-full h-0.5 bg-[hsl(var(--primary))]"></span>
            </Link>
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="mb-12 text-center">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4 tracking-tight">SimpleMesh.AI Terms of Use</h1>
          <p className="text-[hsl(var(--muted-foreground))] text-lg">Last Updated: November 4, 2024</p>
        </div>

        <div className="space-y-8">
          {/* Introduction */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">Introduction</h2>
            <p className="text-[hsl(var(--foreground))]/90 mb-4">
              These AI Terms of Use (this "Agreement") are a binding contract between you or the entity you represent ("Customer," "you," or "your") and simplemesh LLC ("Provider," "we," or "us"). This Agreement governs your access to and use of the Services. Services provided under this Agreement are for business or commercial, and not personal or consumer, use.
            </p>
            <p className="text-[hsl(var(--foreground))]/90">
              THIS AGREEMENT TAKES EFFECT WHEN YOU CLICK THE "Continue" BUTTON TO ESTABLISH ACCESS AND USE THE SERVICES FOR THE FIRST TIME (the "Effective Date"). BY CLICKING ON THE "Continue" BUTTON OR ACCESSING OR USING THE SERVICES YOU ACCEPT THIS AGREEMENT AND AGREE THAT YOU ARE LEGALLY BOUND BY ITS TERMS.
            </p>
            <p className="text-[hsl(var(--foreground))]/90 mt-4 font-medium">
              IF YOU DO NOT ACCEPT THESE TERMS, YOU MAY NOT ACCESS OR USE THE SERVICES.
            </p>
          </div>

          {/* Definitions */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">1. Definitions</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              "Aggregated Statistics" has the meaning set out in Section 2(d).

              "AI Customer Input" means information, data, materials, text, prompts, images, works, code, or other content that is input, entered, posted, uploaded, submitted, transferred, or otherwise transmitted by or on behalf of Customer or any other Authorized User through the Services.

              "AI Customer Output" means information, data, materials, text, images, code, works, or other content generated by or otherwise output from the Services in response to an AI Customer Input.

              "AI Technology" means any and all machine learning, deep learning, and other artificial intelligence technologies, including statistical learning algorithms, models (including large language models), neural networks, and other artificial intelligence tools or methodologies.

              "API" means any application programming interface Provider makes available in connection with the Services as described on Provider's website available at https://www.simplemesh.ai/api.

              "AUP" has the meaning set out in Section 3(a).

              "Authorized User" means Customer and Customer's employees, consultants, contractors, and agents who are authorized by Customer to access and use the Services under the rights granted to Customer under this Agreement.

              "Customer Data" means AI Customer Input and AI Customer Output. Customer Data does not include Aggregated Statistics.

              "Documentation" means Provider's end user documentation relating to the Services available at https://docs.simplemesh.ai/.

              "Feedback" has the meaning set out in Section 8(d).

              "Fees" has the meaning set out in Section 5.
            </div>
          </div>

          {/* Access and Use */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">2. Access and Use</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              (a) Provision of Access. Subject to the terms and conditions of this Agreement, Provider hereby grants you a non-exclusive, non-transferable right to access and use the Services during the Term, solely for your internal business operations by Authorized Users under these terms and conditions.

              (b) Documentation License. Subject to the terms and conditions contained in this Agreement, Provider hereby grants you a non-exclusive, non-sublicensable, non-transferable license for Authorized Users to use the Documentation during the Term solely for your internal business purposes in connection with use of the Services.

              (c) Use Restrictions. You shall not use the Services for any purposes beyond the scope of the access granted in this Agreement. You shall not at any time, directly or indirectly, and shall not permit any Authorized Users to: (i) copy, modify, or create derivative works of the Services or Documentation; (ii) rent, lease, lend, sell, license, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services or Documentation; (iii) reverse engineer, disassemble, decompile, decode, or duplicate the Services; or (iv) remove any proprietary notices from the Services or Documentation.

              (d) Aggregated Statistics. Notwithstanding anything to the contrary in this Agreement, Provider may monitor Customer's use of the Services and collect and compile data and information related to Customer's use of the Services to be used by Provider in an aggregated and anonymized manner ("Aggregated Statistics"). As between Provider and Customer, all right, title, and interest in Aggregated Statistics, and all intellectual property rights therein, belong to and are retained solely by Provider.

              (e) Reservation of Rights. Provider reserves all rights not expressly granted to Customer in this Agreement.

              (f) Suspension. Provider may temporarily suspend Customer's and any other Authorized User's access to any portion or all of the Services if Provider reasonably determines that there is a threat to the security of the Provider IP or if Customer is in material violation of this Agreement.
            </div>
          </div>

          {/* Customer Responsibilities */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">3. Customer Responsibilities</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              (a) Acceptable Use Policy. The Services may not be used for unlawful, fraudulent, offensive, or obscene activity, as described in Provider's acceptable use policy ("AUP") located at https://www.simplemesh.ai/acceptable-use-policy.

              (b) Account Use. You are responsible and liable for all uses of the Services and Documentation resulting from access provided by you, directly or indirectly, whether that access or use is permitted by or in violation of this Agreement.

              (c) Use of AI Customer Output. You are solely responsible for evaluating AI Customer Output for accuracy, completeness, and other factors relevant to your use before using, distributing, or relying on the AI Customer Output.

              (d) Passwords and Access Credentials. You are responsible for keeping your passwords and access credentials associated with the Services confidential. You shall promptly notify us about any unauthorized access to your passwords or access credentials.
            </div>
          </div>

          {/* Fees and Payment */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">4. Fees and Payment</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              Customer shall pay Provider the fees as described on https://www.simplemesh.ai/pricing ("Fees") either immediately or, if expressly agreed by Provider, within thirty (30) days from the invoice date without offset or deduction. Customer shall make all payments hereunder in US dollars. If Customer fails to make any payment when due, Provider may suspend Customer's access to the Services until such amounts are paid in full. All Fees are exclusive of taxes and similar assessments.
            </div>
          </div>

          {/* Intellectual Property */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">5. Intellectual Property Ownership</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              (a) Provider IP. Customer acknowledges that, as between Customer and Provider, Provider owns all right, title, and interest, including all intellectual property rights, in and to the Provider IP.

              (b) Customer Data. Provider acknowledges that, as between Provider and Customer, Customer owns all right, title, and interest, including all intellectual property rights, in and to the Customer Data. Customer hereby grants to Provider a non-exclusive, royalty-free, worldwide license to reproduce, distribute, and otherwise use and display the Customer Data as necessary for Provider to provide the Services to Customer.

              (c) Feedback. If you send or transmit any communications or materials to us suggesting or recommending changes to the Services ("Feedback"), we are free to use that Feedback. All Feedback is and will be treated as non-confidential.
            </div>
          </div>

          {/* Warranty Disclaimer */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">6. Limited Warranty and Warranty Disclaimer</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              THE SERVICES AND AI CUSTOMER OUTPUT ARE PROVIDED "AS IS" AND PROVIDER SPECIFICALLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. PROVIDER SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE.

              PROVIDER MAKES NO WARRANTY OF ANY KIND THAT THE SERVICES, OR ANY PRODUCTS OR RESULTS OF THE USE THEREOF, INCLUDING ANY AI OUTPUTS, WILL MEET YOUR REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, ACHIEVE ANY INTENDED RESULT, BE COMPATIBLE OR WORK WITH ANY SOFTWARE, SYSTEM, OR OTHER SERVICES, OR BE SECURE, ACCURATE, COMPLETE, FREE OF HARMFUL CODE, OR ERROR-FREE.
            </div>
          </div>

          {/* Limitation of Liability */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">7. Limitations of Liability</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              IN NO EVENT WILL PROVIDER BE LIABLE UNDER OR IN CONNECTION WITH THIS AGREEMENT UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, ENHANCED, OR PUNITIVE DAMAGES; INCREASED COSTS, DIMINUTION IN VALUE OR LOST BUSINESS, PRODUCTION, REVENUES, OR PROFITS; LOSS OF GOODWILL OR REPUTATION; USE, INABILITY TO USE, LOSS, INTERRUPTION, DELAY OR RECOVERY OF ANY DATA, OR BREACH OF DATA OR SYSTEM SECURITY.

              IN NO EVENT WILL PROVIDER'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNTS PAID TO PROVIDER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
            </div>
          </div>

          {/* Term and Termination */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">8. Term and Termination</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              (a) Term. The term of this Agreement begins on the Effective Date and continues until terminated.

              (b) Termination. Provider may terminate this Agreement for any reason upon thirty (30) days' advance notice. You may terminate this Agreement for any reason upon sixty (60) days' advance notice.

              (c) Effect of Termination. Upon termination of this Agreement, Customer shall immediately discontinue use of the Provider IP. No termination will affect Customer's obligation to pay all Fees that may have become due before termination, or entitle Customer to any refund.
            </div>
          </div>

          {/* Modifications */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">9. Modifications</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              You acknowledge and agree that we have the right, in our sole discretion, to modify this Agreement from time to time, and that modified terms become effective on posting. You will be notified of modifications through notifications or posts on our website or direct email communication from us. Your continued use of the Services after the effective date of the modifications will be deemed acceptance of the modified terms.
            </div>
          </div>

          {/* Governing Law */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <h2 className="text-xl font-semibold mb-4">10. Governing Law and Jurisdiction</h2>
            <div className="text-[hsl(var(--foreground))]/90 whitespace-pre-line">
              This agreement is governed by and construed in accordance with the laws of the United Kingdom without giving effect to any choice or conflict of law provision or rule. Any legal suit, action, or proceeding arising out of or related to this agreement will be instituted in the courts of England and Wales, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such suit, action, or proceeding.
            </div>
          </div>

          {/* Contact Section */}
          <div className="bg-[hsl(var(--card))] rounded-lg border border-[hsl(var(--border))]/40 p-6 mt-8">
            <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
            <p className="text-[hsl(var(--foreground))]/90 mb-4">
              If you have any questions about these Terms, please contact us at:
            </p>
            <div className="p-4 bg-[hsl(var(--secondary))]/10 rounded-md flex items-center space-x-2">
              <svg className="w-5 h-5 text-[hsl(var(--primary))]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <a href="mailto:notices@simplemesh.ai" className="text-[hsl(var(--primary))] hover:underline">notices@simplemesh.ai</a>
            </div>
          </div>
          
          {/* Agreement Section */}
          <div className="bg-gradient-to-br from-[hsl(var(--primary))]/10 to-[hsl(var(--ring))]/20 rounded-lg border border-[hsl(var(--border))]/40 p-6">
            <div className="flex flex-col md:flex-row items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-semibold mb-2">By using our services, you agree to these terms</h2>
                <p className="text-[hsl(var(--foreground))]/80">Thank you for reviewing our Terms and Conditions</p>
              </div>
              <Link 
                href="/" 
                className="group relative inline-flex items-center justify-center px-6 py-3 text-base font-medium leading-6 text-[hsl(var(--foreground))] transition-all duration-200 ease-in-out bg-[hsl(var(--secondary))]/5 border border-[hsl(var(--border))]/30 rounded-lg hover:bg-[hsl(var(--secondary))]/20 hover:border-[hsl(var(--border))]/50"
              >
                <span className="relative z-10">Return Home</span>
              </Link>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-[hsl(var(--background))]/80 backdrop-blur-md border-t border-[hsl(var(--border))]/20 py-8 mt-16">
        <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center">
          <div className="flex items-center mb-4 md:mb-0">
            <Image src="/favicon/Logo-Fox-Light.svg" alt="Logo" width={28} height={28} className="mr-2" />
            <span className="text-[hsl(var(--foreground))]/70 text-sm">© {new Date().getFullYear()} simplemesh AI. All rights reserved.</span>
          </div>
          <div className="flex space-x-6">
            <Link href="/privacy" className="text-[hsl(var(--foreground))]/70 hover:text-[hsl(var(--foreground))] text-sm">
              Privacy Policy
            </Link>
            <Link href="/terms-and-conditions" className="text-[hsl(var(--primary))] hover:text-[hsl(var(--primary))]/80 text-sm font-medium">
              Terms of Service
            </Link>
            <Link href="/contact" className="text-[hsl(var(--foreground))]/70 hover:text-[hsl(var(--foreground))] text-sm">
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}